#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::RealBin"; # use the location of script

# Check if BUILDTOP is set
die "BUILDTOP is not set.\n" unless defined $ENV{BUILDTOP};

die "1 and only 1 argument is needed, unless 1st argument is '--'.\n" unless
defined @ARGV;

if (scalar @ARGV > 1)
{
    if ($ARGV[0] ne '--')
    {
        die "More than 1 argument specified but 1st argument is not '--'.\n";
    }
    elsif (not defined $ARGV[2])
    {
        die "Need at least 1 source file after test case name.\n";
    }
}
elsif ($ARGV[0] eq '--')
{
    die "Need 1 test case and at least 1 source file after '--'.\n";
}

exec "$FindBin::RealBin/ut_test_launcher", $FindBin::Script, @ARGV;
